# Generated by Django 2.1.3 on 2018-11-29 05:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfo',
            name='dep',
            field=models.CharField(default='MTK', max_length=16),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='displayer',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('[AB]-\\d{1}-\\d{4}$', message='格式错误，示例：B-1-0195')]),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='host',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('[AB]-\\d{1}-\\d{4}$', message='格式错误，示例：B-1-0195')]),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='ip_addr',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('\\d{2,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}$', message='格式错误，示例：192.168.24.30')]),
        ),
    ]
