# Generated by Django 2.1.3 on 2018-11-29 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20181129_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.Department'),
        ),
    ]
