# Generated by Django 2.1.3 on 2018-11-29 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20181129_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfo',
            name='commnet',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='displayer',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('[ABC]-\\d{1}-\\d{4}$', message='格式错误，示例：B-1-0195')]),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='host',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('[ABC]-\\d{1}-\\d{4}$', message='格式错误，示例：B-1-0195')]),
        ),
    ]
