# Generated by Django 2.1.3 on 2018-11-29 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_auto_20181129_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostinfo',
            old_name='commnet',
            new_name='comment',
        ),
    ]
